[package]
name = "git-hooks"
version = "0.1.0"
authors = ["Simon Wörner <git@simon-woerner.de>"]
edition = "2018"

[dev-dependencies]
cargo-husky = { version = "^1.3", default-features = false, features = ["user-hooks"] }