[package]
name = "gramophone"
version = "0.1.0"
authors = ["coco <coco@hexgolems.com>"]

[dependencies]
nix = "0.8.0"
time = "0.1"
subprocess = "0.1.10"
grammartec = {path = "../grammartec"}
forksrv =  {path = "../forksrv"}
antlr_parser = {path = "../antlr_parser"}
libc = "*"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
argparse = "0.2.2"
ron = "*"
clap = "2.32.0"

[[bin]]
name = "fuzzer"
path = "src/main.rs"

[[bin]]
name = "generator"
path = "src/generator.rs"

[[bin]]
name = "mutator"
path = "src/mutation_tester.rs"

[[bin]]
name = "test_runner"
path = "src/test_runner.rs"
